### ISSUE TITLE
Opening the source code

### ISSUE THREAD

**Issue by sskras** [sredna/Freeware#1]
Nice idea, thanks!

This made me interested about the source code. Any ideas of opening it up?

**Comment by sredna** [comment]
Which app?

These are just tools thrown together for minimal file size for my own use, most of them probably have better open source versions you can find elsewhere.

**Comment by sskras** [comment]
Sorry, I mean that [PhysHidCleanAssist](https://github.com/sredna/Freeware#physhidcleanassist).

Sure, other `head` and `strings` implementations can be easily accessed by installing @msys2 or @cygwin.

**Comment by sskras** [comment]
Sorry, I mean [PhysHidCleanAssist](https://github.com/sredna/Freeware#physhidcleanassist).

Sure, other `head` and `strings` implementations can be easily accessed by installing @msys2 or @cygwin.

**Comment by sredna** [comment]
> PhysHidCleanAssist

It just calls `SetWindowsHookEx` to set a low-level hook that eats the input.

**Comment by sskras** [comment]
Thanks for specifics. Probably closing then?
